name: Code Coverage
on:
  push:
    branches:
      - "main"
      - "development"
jobs:
  codecov:
    name: Codecov
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Generate Code Coverage Report
        run: |
          pip install pytest pytest-cov
          pytest --cov=. --cov-report=xml ./tests
      - name: Upload Report to codecov website
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.TORII_CODECOV_TOKEN }}
